[package]
name = "ma8bitemu"
description = "A no-std library for 8-bit processors emulators"
readme = "README.md"
version = "0.1.0"
edition = "2024"

[dependencies]

[features]
std = []

[[bin]]
name = "runcpm"
required-features = ["std"]

[profile.release-line]
inherits = "release"
debug = "line-tables-only"